VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsOrder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public orderId As Long
Public sapId As Long
Public theType As String
Public zfinId As Integer
Public zfinIndex As Long
Public roast As Double
Public ground As Double
Public packed As Double


